"""db schema initial

Revision ID: f1095c4e099a
Revises: 
Create Date: 2025-12-01 02:40:49.122679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1095c4e099a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'key'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_idempotency_tenant_key')
    )
    op.create_index('ix_idempotency_created_at', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'CLOSED', name='orderstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_tenant_created_id', 'orders', ['tenant_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_orders_tenant_id', 'orders', ['tenant_id', 'id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_published_at', 'outbox', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_published_at', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_orders_tenant_id', table_name='orders')
    op.drop_index('ix_orders_tenant_created_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_idempotency_created_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
